<?php
    header("Content-Type: text/html;charset=UTF-8");
    include('conexionBd.php');
    include("class.phpmailer.php");
    mysql_query("SET NAMES 'utf8'");
    $Nombre = ucfirst(strtolower($_POST["nombre"]));
    $Apellido = ucfirst(strtolower($_POST["apellido"]));
    $Correo = strtolower($_POST["correo"]);
    $Telefono = $_POST["telefono"];
    $Comentarios = $_POST["comentarios"];
    $strSQL = "INSERT INTO mensajes (nombre,apellido,correo,telefono,comentarios) VALUES ('".$Nombre."','".$Apellido."','".$Correo."','".$Telefono."','".$Comentarios."')";
    $objQuery = mysql_query($strSQL);
    if($objQuery){
        $Mensaje   = " <!DOCTYPE html>" . "\r\n";
        $Mensaje  .= " <html lang='en'>" . "\r\n";
        $Mensaje  .= " <head>" . "\r\n";
        $Mensaje  .= "     <meta charset='UTF-8'>" . "\r\n";
        $Mensaje  .= "     <meta name='viewport' content='width=device-width, initial-scale=1.0'>" . "\r\n";
        $Mensaje  .= "     <link href='https://fonts.googleapis.com/css?family=Chau+Philomene+One' rel='stylesheet'>" . "\r\n";
        $Mensaje  .= "     <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css'>" . "\r\n";
        $Mensaje  .= "     <title>Document</title>" . "\r\n";
        $Mensaje  .= "     <style>" . "\r\n";
        $Mensaje  .= "          .letra{" . "\r\n";
        $Mensaje  .= "              font-family: 'Chau Philomene One', sans-serif" . "\r\n";
        $Mensaje  .= "          }" . "\r\n";
        $Mensaje  .= "          body{" . "\r\n";
        $Mensaje  .= "              margin: 0px;" . "\r\n";
        $Mensaje  .= "              padding: 0px;" . "\r\n";
        $Mensaje  .= "              background-image: url('http://familyplanet.co/img/email/fdo.gif');" . "\r\n";
        $Mensaje  .= "              background-position: top center;" . "\r\n";
        $Mensaje  .= "          }" . "\r\n";
        $Mensaje  .= "      </style>" . "\r\n";
        $Mensaje  .= " </head>" . "\r\n";
        $Mensaje  .= " <body>" . "\r\n";
        $Mensaje  .= "  <table background='http://familyplanet.co/img/email/fdo.gif' width='600px' height='100%' border='0' align='center' cellpadding='0' cellspacing='0'>" . "\r\n";
        $Mensaje  .= "      <tr>" . "\r\n";
        $Mensaje  .= "          <td>" . "\r\n";
        $Mensaje  .= "              <img src='http://familyplanet.co/img/email/cabezote.gif'/>" . "\r\n";
        $Mensaje  .= "                  <div style='width:400px;margin-left: auto;margin-right: auto;text-align: center;font-size:24px;padding: 10px 0px 20px 0px' class='letra'>" . "\r\n";
        $Mensaje  .= "                      Hola ".$Nombre.", hemos recibido tu solicitud, con la mayor prontitud posible estaremos comunic&aacute;ndonos." . "\r\n";
        $Mensaje  .= "                  </div>" . "\r\n";
        $Mensaje  .= "                  <div style='text-align: center'>" . "\r\n";
        $Mensaje  .= "                      <img src='http://familyplanet.co/img/email/iconos.png'/>" . "\r\n";
        $Mensaje  .= "                  </div>" . "\r\n";
        $Mensaje  .= "         <h3 style='text-align: center;color: #e80e8a' class='letra'>" . "\r\n";
        $Mensaje  .= "                 316 690 5528<br>" . "\r\n";
        $Mensaje  .= "                 Calle 51 # 38-76 <br>" . "\r\n";
        $Mensaje  .= "                 ventas@familyplanet.co <br>" . "\r\n";
        $Mensaje  .= "                 Barranquilla, Colombia" . "\r\n";
        $Mensaje  .= "         </h3>" . "\r\n";
        $Mensaje  .= "         <div style='text-align: center'>" . "\r\n";
        $Mensaje  .= "             <a href='https://www.facebook.com/familyplanetbarranquilla/'><img src='http://familyplanet.co/img/email/iconoFacebook.png'/></a>" . "\r\n";
        $Mensaje  .= "             <a href='https://twitter.com/familyplanetbq/'><img src='http://familyplanet.co/img/email/iconoTwitter.png'/></a>" . "\r\n";
        $Mensaje  .= "             <a href='https://www.instagram.com/familyplanetbq/'><img src='http://familyplanet.co/img/email/iconoInstagram.png'/></a>" . "\r\n";
        $Mensaje  .= "         </div>" . "\r\n";
        $Mensaje  .= "         <img style='text-align: center' src='http://familyplanet.co/img/email/piepagina.png' alt='' />" . "\r\n";
        $Mensaje  .= "         </td>" . "\r\n";
        $Mensaje  .= "     </tr>" . "\r\n";
        $Mensaje  .= "  </table>" . "\r\n";
        $Mensaje  .= " </body>" . "\r\n";
        $Mensaje  .= " </html>" . "\r\n";
        $mail = new PHPMailer();
        $mail->IsSMTP();
        $mail->SMTPAuth = true;
        $mail->Host = "mail.familyplanet.co";
        $mail->Username = "ventas@familyplanet.co";
        $mail->Password = "V5nt1sFp,";
        $mail->From = "ventas@familyplanet.co";
        $mail->FromName = "ventas@familyplanet.co";
        $mail->AddAddress($Correo,$Nombre." ".$Apellido);
        $mail->Subject = "Mensaje";
        $mail->Body = $Mensaje;
        $mail->WordWrap = 50;
        $mail->IsHTML(true);
        if(!$mail->Send()) {
            echo "Mailer Error: ".$mail->ErrorInfo;
            echo "<br><br> * Please double check the user name and password to confirm that both of them are correct. <br><br>";
            echo "* If you are the first time to use gmail smtp to send email, please refer to this link :http://www.smarterasp.net/support/kb/a1546/send-email-from-gmail-with-smtp-authentication-but-got-5_5_1-authentication-required-error.aspx?KBSearchID=137388";
        }else {
        }
        $Mensaje1   = " <!DOCTYPE html>" . "\r\n";
        $Mensaje1  .= " <html lang='en'>" . "\r\n";
        $Mensaje1  .= " <head>" . "\r\n";
        $Mensaje1  .= "     <meta charset='UTF-8'>" . "\r\n";
        $Mensaje1  .= "     <meta name='viewport' content='width=device-width, initial-scale=1.0'>" . "\r\n";
        $Mensaje1  .= "     <link href='https://fonts.googleapis.com/css?family=Chau+Philomene+One' rel='stylesheet'>" . "\r\n";
        $Mensaje1  .= "     <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css'>" . "\r\n";
        $Mensaje1  .= "     <title>Document</title>" . "\r\n";
        $Mensaje1  .= "     <style>" . "\r\n";
        $Mensaje1  .= "          .letra{" . "\r\n";
        $Mensaje1  .= "              font-family: 'Chau Philomene One', sans-serif" . "\r\n";
        $Mensaje1  .= "          }" . "\r\n";
        $Mensaje1  .= "      </style>" . "\r\n";
        $Mensaje1  .= " </head>" . "\r\n";
        $Mensaje1  .= " <body>" . "\r\n";
        $Mensaje1  .= "     <div style='width: 600px;height: 100%;background-image: url(http://familyplanet.co/img/email/fdo.gif)'>" . "\r\n";
        $Mensaje1  .= "         <img src='http://familyplanet.co/img/email/cabezote.gif'/>" . "\r\n";
        $Mensaje1  .= "         <div style='width:400px;margin-left: auto;margin-right: auto;text-align: center;font-size:24px;padding: 10px 0px 20px 0px' class='letra'>" . "\r\n";
        $Mensaje1  .= "             Nombre: ".$Nombre."<br>" . "\r\n";
        $Mensaje1  .= "             Apellido: ".$Apellido."<br>" . "\r\n";
        $Mensaje1  .= "             Correo: ".$Correo."<br>" . "\r\n";
        $Mensaje1  .= "             Tel&eacute;fono: ".$Telefono."<br>" . "\r\n";
        $Mensaje1  .= "             Comentarios: ".$Comentarios."" . "\r\n";
        $Mensaje1  .= "         </div>" . "\r\n";
        $Mensaje1  .= "         <div style='text-align: center'>" . "\r\n";
        $Mensaje1  .= "             <img src='http://familyplanet.co/img/email/iconos.png'/>" . "\r\n";
        $Mensaje1  .= "         </div>" . "\r\n";
        $Mensaje1  .= "         <div style='text-align: center'>" . "\r\n";
        $Mensaje1  .= "             <a href='https://www.facebook.com/familyplanetbarranquilla/'><img src='http://familyplanet.co/img/email/iconoFacebook.png'/></a>" . "\r\n";
        $Mensaje1  .= "             <a href='https://twitter.com/familyplanetbq/'><img src='http://familyplanet.co/img/email/iconoTwitter.png'/></a>" . "\r\n";
        $Mensaje1  .= "             <a href='https://www.instagram.com/familyplanetbq/'><img src='http://familyplanet.co/img/email/iconoInstagram.png'/></a>" . "\r\n";
        $Mensaje1  .= "         </div>" . "\r\n";
        $Mensaje1  .= "         <img style='text-align: center' src='http://familyplanet.co/img/email/piepagina.png' alt='' />" . "\r\n";
        $Mensaje1  .= "     </div>" . "\r\n";
        $Mensaje1  .= " </body>" . "\r\n";
        $Mensaje1  .= " </html>" . "\r\n";
        $mail1 = new PHPMailer();
        $mail1->IsSMTP();
        $mail1->SMTPAuth = true;
        $mail1->Host = "mail.familyplanet.co";
        $mail1->Username = "ventas@familyplanet.co";
        $mail1->Password = "V5nt1sFp,";
        $mail1->From = "ventas@familyplanet.co";
        $mail1->FromName = "ventas@familyplanet.co";
        $mail1->AddAddress("ventas@familyplanet.co","Ventas");
        $mail1->Subject = "Mensaje";
        $mail1->Body = $Mensaje1;
        $mail1->WordWrap = 50;
        $mail1->IsHTML(true);
        if(!$mail1->Send()) {
            echo "Mailer Error: ".$mail1->ErrorInfo;
            echo "<br><br> * Please double check the user name and password to confirm that both of them are correct. <br><br>";
            echo "* If you are the first time to use gmail smtp to send email, please refer to this link :http://www.smarterasp.net/support/kb/a1546/send-email-from-gmail-with-smtp-authentication-but-got-5_5_1-authentication-required-error.aspx?KBSearchID=137388";
        }else {
        }
        echo 1;
    }
    mysql_close($objConnect);
?>
